Add retry logic when reboot fails

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -114,14 +114,31 @@ jobs:
             echo "Attempting to boot simulator with ID: $device_id"
             
             # Wait for the simulator to be fully booted
-            boot_status=$(xcrun simctl list devices | grep "$device_id" | grep 'Booted')
-            if [[ -z "$boot_status" ]]; then
-              echo "Error: Failed to boot simulator: $simulator. Retrying..."
-              xcrun simctl boot "$device_id" || echo "Retry failed for simulator: $simulator"
-            else
+            MAX_RETRIES=3
+            RETRY_COUNT=0
+            while [[ $RETRY_COUNT -lt $MAX_RETRIES ]]; do
+
+              xcrun simctl boot "$device_id"
+    
+              # Wait a few seconds for the simulator to boot
+              sleep 5
+
+              boot_status=$(xcrun simctl list devices | grep "$device_id" | grep 'Booted')
+              
+              if [[ -n "$boot_status" ]]; then
               echo "Simulator $simulator successfully booted."
-            fi
+              break
+              else
+                echo "Failed to boot simulator $simulator. Retrying..."
+                RETRY_COUNT=$((RETRY_COUNT+1))
+              fi
             done
+
+            # If it failed after retries, exit with an error
+            if [[ $RETRY_COUNT -eq $MAX_RETRIES ]]; then
+              echo "Error: Simulator $simulator failed to boot after $MAX_RETRIES attempts."
+              exit 1
+            fi
 
             # Once booted, proceed to the next step
             echo "Simulator $simulator is successfully booted. Proceeding with the next step..."
