Small change to change variable to boot_status

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -114,16 +114,13 @@ jobs:
             echo "Attempting to boot simulator with ID: $device_id"
             
             # Wait for the simulator to be fully booted
-            echo "Waiting for simulator to be fully booted..."
-            while true; do
-              boot_status=$(xcrun simctl list devices | grep "$device_id" | grep -o 'Booted')
-              if [[ "$boot_status" == "Booted" ]]; then
-                echo "Simulator $simulator is fully booted."
-                break
-              else
-                echo "Simulator $simulator is still booting... Retrying..."
-                sleep 10
-              fi
+            boot_status=$(xcrun simctl list devices | grep "$device_id" | grep 'Booted')
+            if [[ -z "$boot_status" ]]; then
+              echo "Error: Failed to boot simulator: $simulator. Retrying..."
+              xcrun simctl boot "$device_id" || echo "Retry failed for simulator: $simulator"
+            else
+              echo "Simulator $simulator successfully booted."
+            fi
             done
 
             # Once booted, proceed to the next step
